export { buildIndex, buildSemanticIndex, tokenise } from './index-builder.js'
export type { TeamLike } from './index-builder.js'
export { search, semanticSearch, cosineSimilarity } from './search.js'
export { route, routeSemantic } from './router.js'
export { embed } from './embed.js'
export type { RouteResult, RouterEntry, RouterIndex, AskResponse } from './types.js'
